[package]
name = "amqp"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false

[dependencies]
lapin.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true

error = { workspace = true, features = ["amqp"] }
types.workspace = true
