[package]
name = "atp"
description = "Actor Transport Protocol client, server, and message types"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
serde_json.workspace = true
serde_valid.workspace = true
serde.workspace = true

uuid.workspace = true
chrono.workspace = true
