services:
  mage-broker:
    build:
      target: builder
    working_dir: /app
    environment:
      CONSOLE_ENABLED: true
      CONSOLE_TENANT_ID: 775a179d-9819-42c0-ab47-637bf96fbf7b
    volumes:
      - .:/app
      - mage-broker-target:/app/target
      - mage-broker-cargo-registry:/usr/local/cargo/registry
    command: cargo run --release --package mage-broker

  mage-worker:
    build:
      target: builder
    working_dir: /app
    environment:
      MAGE_CACHE: /app/.cache
    volumes:
      - .:/app
      - mage-worker-target:/app/target
      - mage-worker-cargo-registry:/usr/local/cargo/registry
      - ./.cache:/app/.cache
    command: cargo run --release --package mage-worker

volumes:
  mage-broker-target:
  mage-worker-target:
  mage-broker-cargo-registry:
  mage-worker-cargo-registry:
