[package]
name = "mage-broker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum = { workspace = true, features = ["http1", "json", "query", "tokio", "tracing", "ws"] }
serde_json.workspace = true
serde_valid.workspace = true
serde.workspace = true
askama = { version = "0.16", features = ["serde_json"] }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
tower = { version = "0.5.3", features = ["make", "util"] }
tower-http = { version = "0.7.0", features = ["fs", "normalize-path"] }
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
chrono.workspace = true
sqlx = { workspace = true, features = ["runtime-tokio", "postgres", "macros", "migrate"] }

atp.workspace = true
mage-amqp.workspace = true
mage-error = { workspace = true, features = ["storage", "web"] }
mage-storage.workspace = true
mage-types.workspace = true
