[package]
name = "error"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[features]
default = []
web = ["dep:axum"]
ai = ["dep:reqwest", "dep:url"]
amqp = ["dep:lapin"]
storage = ["dep:sqlx"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
serde_valid.workspace = true

axum = { workspace = true, features = ["json"], optional = true }
lapin = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
sqlx = { workspace = true, optional = true }
url = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
