[package]
name = "proto"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
tokio = { workspace = true, features = ["net"] }
tokio-tungstenite = { version = "0.30", features = ["rustls-tls-native-roots"] }

serde_json.workspace = true
serde_valid.workspace = true
serde.workspace = true

uuid.workspace = true
chrono.workspace = true
futures-util = { workspace = true, features = ["sink"] }

error.workspace = true
types.workspace = true

[dev-dependencies]
axum = { workspace = true, features = ["http1", "tokio", "ws"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "time"] }
